package com.scanly.backend.service;

/**
 * DDLGenerator — generates CREATE TABLE statements for Tier 1 auto-create mode.
 *
 * Produces two tables:
 *   scanly_invoices    — one row per invoice header
 *   scanly_line_items  — one row per line item (FK → scanly_invoices)
 *
 * Uses IF NOT EXISTS so re-running is always safe (idempotent).
 * Supports PostgreSQL and MySQL dialects.
 */
public final class DDLGenerator {

    private DDLGenerator() {}

    /**
     * Returns the full DDL script to create both tables for the given db type.
     * @param dbType "postgresql" or "mysql"
     */
    public static String generate(String dbType) {
        return switch (dbType.toLowerCase()) {
            case "postgresql" -> POSTGRESQL_DDL;
            case "mysql"      -> MYSQL_DDL;
            default -> throw new IllegalArgumentException(
                "Unsupported dbType for DDL generation: " + dbType);
        };
    }

    // ── PostgreSQL ────────────────────────────────────────────────────────────

    private static final String POSTGRESQL_DDL = """
        -- Auto-generated by Scanly. Safe to re-run (IF NOT EXISTS).
        
        CREATE TABLE IF NOT EXISTS scanly_invoices (
            id                UUID         PRIMARY KEY,
            invoice_number    VARCHAR(100),
            vendor_name       VARCHAR(500),
            vendor_address    TEXT,
            vendor_gstin      VARCHAR(20),
            buyer_name        VARCHAR(500),
            buyer_address     TEXT,
            buyer_gstin       VARCHAR(20),
            invoice_date      DATE,
            due_date          DATE,
            subtotal          NUMERIC(15,2),
            tax_amount        NUMERIC(15,2),
            discount_amount   NUMERIC(15,2),
            total_amount      NUMERIC(15,2),
            currency          VARCHAR(5),
            is_audited        BOOLEAN      DEFAULT FALSE,
            has_errors        BOOLEAN      DEFAULT FALSE,
            is_duplicate      BOOLEAN      DEFAULT FALSE,
            validation_issues TEXT,
            pushed_at         TIMESTAMPTZ  DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS scanly_line_items (
            id            UUID        PRIMARY KEY,
            invoice_id    UUID        NOT NULL REFERENCES scanly_invoices(id) ON DELETE CASCADE,
            description   TEXT,
            hsn_code      VARCHAR(20),
            quantity      NUMERIC(10,3),
            unit_price    NUMERIC(15,2),
            tax_rate      NUMERIC(5,2),
            total_price   NUMERIC(15,2),
            created_at    TIMESTAMPTZ DEFAULT NOW()
        );

        CREATE INDEX IF NOT EXISTS idx_scanly_invoices_invoice_date
            ON scanly_invoices(invoice_date);
        CREATE INDEX IF NOT EXISTS idx_scanly_line_items_invoice_id
            ON scanly_line_items(invoice_id);
        """;

    // ── MySQL ─────────────────────────────────────────────────────────────────

    private static final String MYSQL_DDL = """
        -- Auto-generated by Scanly. Safe to re-run (IF NOT EXISTS).
        
        CREATE TABLE IF NOT EXISTS scanly_invoices (
            id                VARCHAR(36)   NOT NULL PRIMARY KEY,
            invoice_number    VARCHAR(100),
            vendor_name       VARCHAR(500),
            vendor_address    TEXT,
            vendor_gstin      VARCHAR(20),
            buyer_name        VARCHAR(500),
            buyer_address     TEXT,
            buyer_gstin       VARCHAR(20),
            invoice_date      DATE,
            due_date          DATE,
            subtotal          DECIMAL(15,2),
            tax_amount        DECIMAL(15,2),
            discount_amount   DECIMAL(15,2),
            total_amount      DECIMAL(15,2),
            currency          VARCHAR(5),
            is_audited        TINYINT(1)    DEFAULT 0,
            has_errors        TINYINT(1)    DEFAULT 0,
            is_duplicate      TINYINT(1)    DEFAULT 0,
            validation_issues TEXT,
            pushed_at         DATETIME      DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

        CREATE TABLE IF NOT EXISTS scanly_line_items (
            id            VARCHAR(36)  NOT NULL PRIMARY KEY,
            invoice_id    VARCHAR(36)  NOT NULL,
            description   TEXT,
            hsn_code      VARCHAR(20),
            quantity      DECIMAL(10,3),
            unit_price    DECIMAL(15,2),
            tax_rate      DECIMAL(5,2),
            total_price   DECIMAL(15,2),
            created_at    DATETIME     DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_scanly_li_invoice
                FOREIGN KEY (invoice_id) REFERENCES scanly_invoices(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """;
}
